# Generated by Django 3.2.4 on 2021-07-24 22:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('groups', models.TextField()),
                ('last_login', models.DateField()),
                ('first_joined', models.DateField()),
                ('birth_date', models.DateField()),
                ('auth_source', models.IntegerField(choices=[(1, 'Google'), (2, 'Facebook'), (3, 'Apple'), (4, 'Email')])),
            ],
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('verification_code', models.CharField(max_length=100, unique=True)),
                ('smokerid', models.ForeignKey(db_column='smokerid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
                ('supporter_username', models.ForeignKey(db_column='supporter_username', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='SmokerSupporter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('date_linked', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('relationship', models.IntegerField(choices=[(1, 'Family'), (2, 'Friend'), (3, 'Colleague'), (4, 'Significant Other')])),
                ('smokerid', models.ForeignKey(db_column='smokerid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
                ('supporterid', models.ForeignKey(db_column='supporterid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
            ],
        ),
    ]
