# Generated by Django 3.2.4 on 2021-07-24 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210725_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smokersupporter',
            name='smokerid',
        ),
        migrations.RemoveField(
            model_name='smokersupporter',
            name='supporterid',
        ),
        migrations.RemoveField(
            model_name='userconnection',
            name='smokerid',
        ),
        migrations.RemoveField(
            model_name='userconnection',
            name='supporter',
        ),
        migrations.DeleteModel(
            name='SmokerSupporter',
        ),
        migrations.DeleteModel(
            name='UserConnection',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        
    ]
