# Generated by Django 3.2.4 on 2021-07-24 23:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=100, unique=True)),
                ('update_required', models.BooleanField(default=True)),
                ('release_date', models.DateField(auto_now=True)),
                ('notes', models.TextField()),
                ('is_latest', models.BooleanField(default=True)),
            ],
        ),
    ]
