# Generated by Django 3.1.6 on 2021-09-02 22:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('smoke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.IntegerField(choices=[(1, 'Campaign'), (2, 'Entry'), (3, 'Other')])),
                ('time', models.TimeField()),
                ('term', models.IntegerField(blank=True, null=True)),
                ('smokeconfig', models.ForeignKey(db_column='smokeconfigid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='smoke.smokeconfig')),
                ('smokersupporter', models.ForeignKey(db_column='smokersupporterid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.smokersupporter')),
            ],
        ),
        migrations.CreateModel(
            name='NotifLaunch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('content', models.CharField(max_length=150)),
                ('launch_date', models.DateTimeField(auto_now_add=True)),
                ('notif_type', models.IntegerField(choices=[(1, 'Campaign'), (2, 'Entry'), (3, 'Other')])),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='NotifDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('notifconfig', models.ForeignKey(db_column='notifconfigid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='notification.notifconfig')),
            ],
        ),
    ]
