# Generated by Django 3.1.6 on 2021-09-02 22:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmokeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.IntegerField(choices=[(1, 'Pack 1'), (2, 'Pack More'), (3, 'Pack Half'), (4, 'Few')])),
                ('cost_per_pack', models.FloatField()),
                ('currency', models.IntegerField(choices=[(1, 'Lira'), (2, 'Dollar'), (3, 'Euro'), (4, 'Yen'), (5, 'Other')])),
                ('smoking_type', models.IntegerField(choices=[(1, 'Pack 1'), (2, 'Pack More'), (3, 'Pack Half'), (4, 'Few')])),
                ('brand', models.IntegerField(choices=[(1, 'Marlboro'), (2, 'Kent'), (3, 'Camel'), (4, 'Davidoff'), (5, 'Other')])),
                ('quit_date', models.DateTimeField(auto_now_add=True)),
                ('years_smoked', models.IntegerField()),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='SmokeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('smoked', models.IntegerField()),
                ('cravings', models.IntegerField()),
                ('intensity', models.IntegerField(choices=[(1, 'Low'), (2, 'Mild'), (3, 'High'), (4, 'Extreme')])),
                ('date', models.DateField(auto_now_add=True)),
                ('date_filled', models.DateField(auto_now_add=True)),
                ('smokeconfig', models.ForeignKey(db_column='smokeconfigid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='smoke.smokeconfig')),
            ],
        ),
    ]
